### ISSUE TITLE
CP2102 pin DTR or DSR?

### ISSUE THREAD

**Issue by K4KDR** [jgromes/ESP32-1W-GroundStation#1]
Hello! 

Bob, N6RFM, has been a tremendous help to me in acquiring the parts and the custom PCB to build your project.  It has been great fun and a real challenge.

As I was reviewing the pin connections to the CP2102, a question has come up.

Across the top row, on the schematic (see image below), the 'DSR' pin (3rd from the left) is not used.

![2102-schematic](https://user-images.githubusercontent.com/19886368/106376146-3aea4380-638a-11eb-896a-6db404ee82b8.png)

.
... however, on the PCB, it is the SECOND pin from the left that appears to be not used:

![2102-zoom](https://user-images.githubusercontent.com/19886368/106376154-548b8b00-638a-11eb-9fef-9e184d1ec689.png)

... could you please let us know which is correct, and what we should do to correct the situation (if any correction is needed)?

Many thanks!

-Scott,  K4KDR

**Comment by jgromes** [comment]
It's actually the same pin -  DTR, pin 28 on the package. On the schematic, the left-most pin is the thermal pad, connected to GND.

**Comment by K4KDR** [comment]
Thank you SO much for the reply!

I had not noticed that the schematic's top row took the liberty of displaying -8- connections while there are only 7 real pin connections.  So, as you said, that ground connection is not actually along that side of the device.

Appreciate the guidance!!
